apiVersion: v1
kind: Secret
metadata:
  name: foodhub-secrets
  namespace: foodhub-dev
type: Opaque
stringData:  # SỬ DỤNG stringData ĐỂ TRÁNH LỖI MÃ HÓA THỦ CÔNG
  DB_ADMIN_PASSWORD: "FoodHub12345"
  DB_PASSWORD_USERS: "Password_users_123"
  DB_PASSWORD_PRODUCTS: "Password_products_123"
  DB_PASSWORD_ORDERS: "Password_orders_123"
  # Dán chuỗi JWT dài vào giữa dấu ngoặc kép, không được xuống dòng
  JWT_SECRET_KEY: "dGhwY3kxcGN5MWhMWE5sWTNKbGRDMXJaWGt0Wm05eUxXcDNkQzFoZFhSb1pXNTBhV05oZEdsdmJpMXBiaTFrWlhaelpXTnZjSE10Y0hKdmFtVmpkQzF0ZFhOMExXSmxMWFpsY25rdGJHOXVaeTFoYm1RdGMyVmpkWEps"
  SPRING_MAIL_PASSWORD: "knfz pbig grvg yitz"
  GOOGLE_CLIENT_ID: "210099132466-tld27udkcs4krtmuthp78281g0ibjfja.apps.googleusercontent.com"
  GOOGLE_CLIENT_SECRET: "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"
